
// Movie Actions

export const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES";
export const GET_UPCOMING_MOVIES = "GET_UPCOMING_MOVIES";
export const GET_TOP_RATED_MOVIES = "GET_TOP_RATED_MOVIES";
export const GET_NOW_PLAYING_MOVIES = "GET_NOW_PLAYING_MOVIES";
export const GET_TRENDING_MOVIES = "GET_TRENDING_MOVIES";
export const GET_MOVIE_DETAILS = "GET_MOVIE_DETAILS";

// Credit Actions

export const GET_MOVIE_CREDITS = "GET_MOVIE_CREDITS";
export const GET_TV_CREDITS = "GET_TV_CREDITS";

// Search Actions

export const GET_SEARCH_RESULTS = "GET_SEARCH_RESULTS";

// TV Actions

export const GET_AIRING_TODAY_TVSHOWS = "GET_AIRING_TODAY_TVSHOWS";
export const GET_POPULAR_TVSHOWS = "GET_POPULAR_TVSHOWS";
export const GET_TOP_RATED_TVSHOWS = "GET_TOP_RATED_TVSHOWS";
export const GET_TRENDING_TVSHOWS = "GET_TRENDING_TVSHOWS";
export const GET_TVSHOW_DETAILS = "GET_TVSHOW_DETAILS";

// Media Type Actions

export const SET_MEDIA_TYPE_MOVIE = "SET_MEDIA_TYPE_MOVIE";
export const SET_MEDIA_TYPE_TV = "SET_MEDIA_TYPE_TV";

// People Actions

export const GET_PERSON_DETAILS = "GET_PERSON_DETAILS";